/* dsh-context client bundle — generated by scripts/build.mjs from src/client/ */
window.__ModuleLoader__.load({
  id: "dsh-context",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
"use strict";

// src/client/i18n.ts
var DICT_ZH = {
  "tab": "\u4E0A\u4E0B\u6587",
  "cat.system": "\u7CFB\u7EDF\u63D0\u793A",
  "cat.tools": "\u5DE5\u5177\u5B9A\u4E49",
  "cat.user": "\u7528\u6237\u6D88\u606F",
  "cat.inject": "\u6CE8\u5165\u4E0A\u4E0B\u6587",
  "cat.assistant": "\u52A9\u624B\u56DE\u590D",
  "cat.tool": "\u5DE5\u5177\u7ED3\u679C",
  "overview.title": "\u5F53\u524D\u6784\u6210",
  "overview.ofWindow": "tokens\uFF08\u7EA6 {p}%\uFF09",
  "overview.estimate": "tokens\uFF08\u4F30\u7B97\uFF09",
  "overview.free": "\u5269\u4F59\u7A97\u53E3",
  "overview.splitEst": "\xB7 \u5206\u7C7B\u6309\u4F30\u7B97\u6BD4\u4F8B\u5206\u914D",
  "overview.ofUsed": "\u5360\u5DF2\u7528\u4E0A\u4E0B\u6587",
  "stats.title": "\u4E0A\u4E0B\u6587\u7EDF\u8BA1",
  "stats.hint": "\u7EDF\u8BA1\u5F53\u524D\u4FDD\u7559\u7684\u5386\u53F2\u7A97\u53E3\uFF08\u4E0E\u8D8B\u52BF\u56FE\u4E00\u81F4\uFF09",
  "stats.turns": "\u8F6E\u6B21",
  "stats.steps": "\u6B65\u6570",
  "stats.injects": "\u6CE8\u5165",
  "stats.compactions": "\u538B\u7F29",
  "stats.prunes": "\u526A\u679D",
  "plugin.title": "\u63D2\u4EF6\u4FE1\u606F",
  "plugin.hint": "The best DSH context plugin \u2B50",
  "plugin.name": "\u63D2\u4EF6",
  "plugin.github": "GitHub",
  "tools.top": "\u5DE5\u5177\u5B9A\u4E49 Top\uFF1A",
  "tools.more": "\u7B49 {n} \u4E2A",
  "trend.title": "\u5386\u53F2\u8D8B\u52BF",
  "gran.step": "\u6B65\u9AA4",
  "gran.turn": "\u8F6E\u6B21",
  "trend.hint": "\u60AC\u505C\u67E5\u770B\u8BE6\u60C5\uFF0C\u2702 \u8868\u793A\u538B\u7F29/\u526A\u679D\uFF0CStep/Turn \u5207\u6362\u7C92\u5EA6",
  "trend.empty": "\u53D1\u8D77\u4E00\u8F6E\u5BF9\u8BDD\u540E\uFF0C\u8FD9\u91CC\u4F1A\u5C55\u793A\u6BCF\u6B21\u6A21\u578B\u8BF7\u6C42\u7684\u4E0A\u4E0B\u6587\u6784\u6210",
  "detail.step": "\u7B2C {t} \u8F6E \xB7 \u7B2C {s} \u6B65",
  "detail.turn": "\u7B2C {t} \u8F6E \xB7 \u5171 {n} \u6B65",
  "detail.lastStep": "\u672B\u6B65",
  "detail.estTotal": "\u4F30\u7B97\u5408\u8BA1 \u2248 {n}",
  "detail.actual": "\u5B9E\u9645 prompt {n}",
  "detail.output": "\u8F93\u51FA {n}",
  "events.title": "\u4E0A\u4E0B\u6587\u4E8B\u4EF6",
  "events.empty": "\u6682\u65E0\u4E0A\u4E0B\u6587\u4E8B\u4EF6\uFF08\u538B\u7F29\u3001\u6CE8\u5165\u3001\u6A21\u578B\u5207\u6362\u4F1A\u51FA\u73B0\u5728\u8FD9\u91CC\uFF09",
  "events.at": "\u7B2C {t} \u8F6E \xB7 \u7B2C {s} \u6B65",
  "events.range": "\u7B2C {t} \u8F6E \xB7 \u7B2C {a}\u2192{b} \u6B65",
  "events.rangeTo": "\u7B2C {a} \u8F6E \xB7 \u7B2C {as} \u6B65 \u2192 \u7B2C {b} \u8F6E \xB7 \u7B2C {bs} \u6B65",
  "kind.inject": "\u6CE8\u5165",
  "kind.compaction": "\u538B\u7F29",
  "kind.prune": "\u526A\u679D",
  "kind.model": "\u5207\u6362",
  "nodes.title": "\u6D88\u606F\u6784\u6210",
  "nodes.hint": "\u5F53\u524D\u6A21\u578B\u53EF\u89C1\u7684\u6D88\u606F\uFF0C\u6700\u65B0\u5728\u524D",
  "nodes.more": "\u2026 \u66F4\u65E9\u7684 {n} \u6761\u6D88\u606F\u5DF2\u7701\u7565",
  "nodes.empty": "\u5F53\u524D\u6CA1\u6709\u6A21\u578B\u53EF\u89C1\u7684\u6D88\u606F",
  "loading": "\u6B63\u5728\u8BFB\u53D6\u4F1A\u8BDD\u65E5\u5FD7\u2026",
  "error": "\u4E0A\u4E0B\u6587\u6570\u636E\u8BFB\u53D6\u5931\u8D25\uFF1A",
  "footer": "\u4F30\u7B97\u53E3\u5F84\uFF1A\u4E0E dsh \u5185\u7F6E tokenMeter \u76F8\u540C\u7684\u56FA\u5B9A\u5BC6\u5EA6\u542F\u53D1\u5F0F\uFF08\u7EA6 4 \u5B57\u7B26 \u2248 1 token\uFF09\uFF1B\u300C\u5B9E\u9645\u300D\u4E3A\u4F9B\u5E94\u5546\u4E0A\u62A5\u7528\u91CF\u3002",
  "tip.step": "\u7B2C {t} \u8F6E \xB7 \u7B2C{s}\u6B65",
  "tip.turn": "\u7B2C {t} \u8F6E \xB7 \u5171 {n} \u6B65",
  "tip.total": "\u5408\u8BA1 \u2248 {n}",
  "tip.actual": "\uFF08\u5B9E\u9645 {n}\uFF09",
  "ev.compaction": "\u538B\u7F29\u4E0A\u4E0B\u6587\uFF08\u6458\u8981\u66FF\u6362 {n} \u6761\u6D88\u606F\uFF09",
  "ev.prune": "\u526A\u679D\u5DE5\u5177\u8F93\u51FA",
  "ev.skill": "Skill \u6CE8\u5165\uFF08{name}\uFF09",
  "ev.model": "\u6A21\u578B\u5207\u6362\uFF1A{a} \u2192 {b}",
  "form.instructions": "\u6307\u4EE4\u6CE8\u5165",
  "form.catalog": "\u76EE\u5F55\u66F4\u65B0",
  "form.snapshot": "\u72B6\u6001\u5FEB\u7167",
  "form.notice": "\u901A\u77E5",
  "form.relay": "\u4EE3\u7406\u8F6C\u53D1",
  "form.recall": "\u5386\u53F2\u53EC\u56DE",
  "form.context": "\u4E0A\u4E0B\u6587\u6CE8\u5165",
  "node.toolResult": "\u5DE5\u5177\u7ED3\u679C",
  "node.calls": "\u8C03\u7528 ",
  "node.empty": "(\u7A7A\u56DE\u590D)",
  "node.nonText": "(\u975E\u6587\u672C\u6D88\u606F)",
  "node.snapshot": "\u5FEB\u7167: ",
  "cmd.desc": "\u67E5\u770B\u4E0A\u4E0B\u6587\u7684\u6784\u6210\u548C\u53D8\u5316",
  "cmd.close": "\u5173\u95ED",
  "browser.title": "\u4E0A\u4E0B\u6587\u6D4F\u89C8\u5668",
  "browser.live": "\u5F53\u524D\uFF08\u4E0B\u4E00\u6B21\u8BF7\u6C42\uFF09",
  "browser.liveNow": "\u5F53\u524D \xB7 \u4E0B\u4E00\u6B21\u8BF7\u6C42",
  "browser.items": "{n} \u9879",
  "browser.missingLive": "\u2026 \u53E6\u6709 {n} \u6761\u66F4\u65E9\u7684\u6D88\u606F\u4E5F\u5728\u4E0A\u4E0B\u6587\u4E2D\uFF08\u8D85\u51FA\u5C55\u793A\u7A97\u53E3\uFF09",
  "browser.approx": "\u8BE5\u6B65\u9AA4\u6D89\u53CA\u7684\u90E8\u5206\u5DF2\u79FB\u9664\u6D88\u606F\u8D85\u51FA\u4FDD\u7559\u8303\u56F4\uFF0C\u4EE5\u4E0B\u4E3A\u8FD1\u4F3C\u6784\u6210",
  "browser.noHeader": "\u6B64\u6570\u636E\u6765\u81EA\u65E7\u7248\u63D2\u4EF6\uFF1A\u4EC5\u63D0\u4F9B token \u4F30\u7B97\uFF0C\u65E0\u5B9E\u9645\u5185\u5BB9",
  "browser.noEpoch": "\u8BE5\u6B65\u9AA4\u7684\u5934\u90E8\u5185\u5BB9\uFF08\u7CFB\u7EDF\u63D0\u793A / \u5DE5\u5177\u5B9A\u4E49\uFF09\u4E0D\u5728\u4FDD\u7559\u8303\u56F4\u5185",
  "browser.noContent": "\u5B8C\u6574\u5185\u5BB9\u4E0D\u5728\u5F53\u524D\u52A0\u8F7D\u7684\u6D88\u606F\u7A97\u53E3\u5185\uFF08\u5728\u804A\u5929\u9875\u52A0\u8F7D\u66F4\u65E9\u5386\u53F2\u540E\u53EF\u67E5\u770B\uFF09",
  "browser.loading": "\u6B63\u5728\u4ECE\u66F4\u65E9\u7684\u4F1A\u8BDD\u5386\u53F2\u52A0\u8F7D\u5B8C\u6574\u5185\u5BB9\u2026",
  "browser.preview": "\u9884\u89C8"
};
var DICT_EN = {
  "tab": "Context",
  "cat.system": "System",
  "cat.tools": "Tool schemas",
  "cat.user": "User",
  "cat.inject": "Injected",
  "cat.assistant": "Assistant",
  "cat.tool": "Tool results",
  "overview.title": "Current composition",
  "overview.ofWindow": "tokens (~{p}%)",
  "overview.estimate": "tokens (estimated)",
  "overview.free": "Free window",
  "overview.splitEst": "\xB7 category split is estimated",
  "overview.ofUsed": "of used context",
  "stats.title": "Context stats",
  "stats.hint": "Over the retained history window (same as the History chart)",
  "stats.turns": "Turns",
  "stats.steps": "Steps",
  "stats.injects": "Injections",
  "stats.compactions": "Compactions",
  "stats.prunes": "Prunes",
  "plugin.title": "Plugin info",
  "plugin.hint": "The best DSH context plugin \u2B50",
  "plugin.name": "Plugin",
  "plugin.github": "GitHub",
  "tools.top": "Top tool schemas:",
  "tools.more": "of {n}",
  "trend.title": "History",
  "gran.step": "Step",
  "gran.turn": "Turn",
  "trend.hint": "hover a bar for details (click to pin), \u2702 marks compaction/prune; scroll sideways to see earlier; Step/Turn switches granularity",
  "trend.empty": "Send a message and each model request\u2019s context makeup shows up here",
  "detail.step": "Turn {t} \xB7 Step {s}",
  "detail.turn": "Turn {t} \xB7 {n} steps",
  "detail.lastStep": "last step",
  "detail.estTotal": "estimated \u2248 {n}",
  "detail.actual": "actual prompt {n}",
  "detail.output": "output {n}",
  "events.title": "Context events",
  "events.empty": "No context events yet (compaction, injections, model switches appear here)",
  "events.at": "Turn {t} \xB7 Step {s}",
  "events.range": "Turn {t} \xB7 Step {a}\u2192{b}",
  "events.rangeTo": "Turn {a} \xB7 Step {as} \u2192 Turn {b} \xB7 Step {bs}",
  "kind.inject": "Inject",
  "kind.compaction": "Compact",
  "kind.prune": "Prune",
  "kind.model": "Switch",
  "nodes.title": "Messages",
  "nodes.hint": "currently model-visible, newest first",
  "nodes.more": "\u2026 {n} earlier messages omitted",
  "nodes.empty": "No model-visible messages right now",
  "loading": "Reading the session log\u2026",
  "error": "Failed to read context data: ",
  "footer": "Estimate: same fixed-density heuristic as dsh\u2019s built-in tokenMeter (~4 chars \u2248 1 token); \u201Cactual\u201D is provider-reported usage.",
  "tip.step": "Turn {t} \xB7 Step {s}",
  "tip.turn": "Turn {t} \xB7 {n} steps",
  "tip.total": "total \u2248 {n}",
  "tip.actual": " (actual {n})",
  "ev.compaction": "Context compacted (summary replaced {n} messages)",
  "ev.prune": "Tool output pruned",
  "ev.skill": "Skill injected ({name})",
  "ev.model": "Model switched: {a} \u2192 {b}",
  "form.instructions": "Instructions",
  "form.catalog": "Catalog update",
  "form.snapshot": "State snapshot",
  "form.notice": "Notice",
  "form.relay": "Agent relay",
  "form.recall": "Recall",
  "form.context": "Context injection",
  "node.toolResult": "Tool result",
  "node.calls": "calls ",
  "node.empty": "(empty reply)",
  "node.nonText": "(non-text message)",
  "node.snapshot": "snapshot: ",
  "cmd.desc": "View context makeup and how it evolves",
  "cmd.close": "Close",
  "browser.title": "Context browser",
  "browser.live": "Live (next request)",
  "browser.liveNow": "Live \xB7 next request",
  "browser.items": "{n} items",
  "browser.missingLive": "\u2026 {n} earlier messages are also part of the context (outside the served window)",
  "browser.approx": "Some removed messages of this step exceed retention \u2014 the makeup below is approximate",
  "browser.noHeader": "Served by an older plugin build: token estimates only, no content",
  "browser.noEpoch": "The header content (system prompt / tool schemas) of this step is outside retention",
  "browser.noContent": "Full content is outside the loaded message window (load older history in Chat to view)",
  "browser.loading": "Loading full content from older session history\u2026",
  "browser.preview": "preview"
};

// src/client/modalStore.ts
var stores = /* @__PURE__ */ new Map();
function modalStoreOf(sessionId) {
  const existing = stores.get(sessionId);
  if (existing !== void 0) return existing;
  let open = false;
  const listeners = /* @__PURE__ */ new Set();
  const store = {
    subscribe(listener) {
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    },
    getSnapshot: () => open,
    set(next) {
      if (next === open) return;
      open = next;
      for (const listener of listeners) listener();
    }
  };
  stores.set(sessionId, store);
  return store;
}
var pendingConsume = /* @__PURE__ */ new Map();
function setPendingConsume(sessionId, guard) {
  pendingConsume.set(sessionId, guard);
}
function takePendingConsume(sessionId) {
  const guard = pendingConsume.get(sessionId);
  if (guard !== void 0) pendingConsume.delete(sessionId);
  return guard;
}

// src/client/command.ts
var COMMAND = "context";
var LINE = "/" + COMMAND;
function registerContextCommand(ctx, kit) {
  ctx.effect(() => {
    const inputTriggers = ctx.get("inputTriggers");
    if (inputTriggers === void 0) return () => {
    };
    return inputTriggers.registerSource({
      trigger: "/",
      name: COMMAND,
      order: 1,
      candidates: (_session, req) => {
        if (req.position !== "leading") return Promise.resolve([]);
        const query = req.query.trim().toLowerCase();
        if (query !== "" && !COMMAND.startsWith(query)) return Promise.resolve([]);
        return Promise.resolve([{ name: COMMAND, description: kit.t("cmd.desc") }]);
      },
      onPick: (pick) => {
        setPendingConsume(pick.session.sessionId, { kind: "span", span: pick.span });
        modalStoreOf(pick.session.sessionId).set(true);
        return "handled";
      },
      matchEnter: (session, line) => {
        if (line !== LINE) return Promise.resolve(void 0);
        setPendingConsume(session.sessionId, { kind: "bare-token", token: LINE });
        modalStoreOf(session.sessionId).set(true);
        return Promise.resolve("handled");
      }
    });
  }, "dsh-context: /context command");
}

// src/client/categories.ts
var CATS = [
  { key: "system", color: "#6366f1" },
  { key: "tools", color: "#f59e0b" },
  { key: "user", color: "#22c55e" },
  { key: "inject", color: "#a855f7" },
  { key: "assistant", color: "#3b82f6" },
  { key: "tool", color: "#14b8a6" }
];
function partsOf(breakdown) {
  return CATS.map((c) => {
    return { key: c.key, color: c.color, value: breakdown[c.key] || 0 };
  });
}
function anchoredParts(parts, target) {
  if (target === null || target <= 0) return parts;
  let total = 0;
  for (const p of parts) total += p.value;
  if (total <= 0 || total === target) return parts;
  const scale = target / total;
  return parts.map((p) => ({ ...p, value: Math.round(p.value * scale) }));
}

// src/client/headline.ts
function headlineOf(data, pressure = null) {
  const current = data.current;
  const projected = pressure !== null && typeof pressure.projectedTokens === "number" ? pressure.projectedTokens : void 0;
  const requests = data.requests || [];
  const lastReq = requests.length > 0 ? requests[requests.length - 1] : null;
  const derived = lastReq !== null && typeof lastReq.prompt === "number" ? lastReq.prompt + (current.total - lastReq.total) : void 0;
  const occupancyTokens = projected ?? derived ?? null;
  const window2 = pressure !== null && typeof pressure.contextWindow === "number" ? pressure.contextWindow : data.contextWindow;
  const tokens = occupancyTokens ?? current.total;
  const pct = window2 !== void 0 && window2 > 0 ? Math.min(100, Math.round(tokens / window2 * 100)) : null;
  const parts = anchoredParts(partsOf(current), occupancyTokens !== null && tokens > 0 ? tokens : null);
  return { tokens, window: window2, pct, parts, estimated: occupancyTokens === null };
}

// src/client/services.ts
function timelineOf(value) {
  if (value === null || value === void 0 || typeof value !== "object") return null;
  return value;
}
function contextPressureOf(value) {
  if (value === null || value === void 0 || typeof value !== "object") return null;
  return value;
}
function headersOf(value) {
  if (value === null || value === void 0 || typeof value !== "object") return null;
  const headers = value.headers;
  if (!Array.isArray(headers)) return null;
  return value;
}

// src/client/react.ts
var React = require("react");
var h = React.createElement;

// src/client/components/requestDetail.tsx
function makeRequestDetail(kit, StackedBar) {
  const { t, tr, fmt: fmt3, fmtTime: fmtTime2, catLabel, eventLabel, eventAt } = kit;
  return function RequestDetail(props) {
    const req = props.request;
    if (!req) return null;
    const isTurn = req.stepCount !== void 0 && req.stepCount > 1;
    const head = isTurn ? tr("detail.turn", { t: req.turn ?? 0, n: req.stepCount ?? 0 }) : tr("detail.step", { t: req.turn ?? 0, s: req.step ?? 0 });
    const marker = props.marker ?? null;
    const markerAt = marker !== null ? eventAt(marker) : null;
    return /* @__PURE__ */ React.createElement("div", { className: "lc-detail" }, /* @__PURE__ */ React.createElement("div", { className: "lc-detail-head" }, /* @__PURE__ */ React.createElement("b", null, head), marker !== null && markerAt !== null ? /* @__PURE__ */ React.createElement("span", { className: "lc-detail-marker", title: eventLabel(marker) }, "\u2702 " + markerAt) : null, isTurn ? /* @__PURE__ */ React.createElement("span", { className: "lc-detail-tag" }, t("detail.lastStep")) : null, /* @__PURE__ */ React.createElement("span", null, fmtTime2(req.time)), /* @__PURE__ */ React.createElement("span", null, tr("detail.estTotal", { n: fmt3(req.total) })), req.prompt !== void 0 ? /* @__PURE__ */ React.createElement("span", { className: "lc-actual" }, tr("detail.actual", { n: fmt3(req.prompt) })) : null, req.output !== void 0 ? /* @__PURE__ */ React.createElement("span", null, tr("detail.output", { n: fmt3(req.output) })) : null), /* @__PURE__ */ React.createElement(StackedBar, { parts: partsOf(req), height: 10 }), /* @__PURE__ */ React.createElement("div", { className: "lc-detail-rows" }, CATS.map((c) => {
      const v = req[c.key] || 0;
      return /* @__PURE__ */ React.createElement("div", { key: c.key, className: "lc-detail-row" }, /* @__PURE__ */ React.createElement("i", { style: { background: c.color } }), /* @__PURE__ */ React.createElement("span", { className: "lc-detail-label" }, catLabel(c.key)), /* @__PURE__ */ React.createElement("span", { className: "lc-bar-track" }, /* @__PURE__ */ React.createElement("span", { className: "lc-bar-fill", style: { width: (req.total > 0 ? v / req.total * 100 : 0) + "%", background: c.color } })), /* @__PURE__ */ React.createElement("span", { className: "lc-detail-num" }, "\u2248" + fmt3(v)), /* @__PURE__ */ React.createElement("span", { className: "lc-detail-pct" }, req.total > 0 ? Math.round(v / req.total * 100) + "%" : ""));
    })));
  };
}

// src/client/components/stackedBar.tsx
function makeStackedBar(kit) {
  const { t, tr, fmt: fmt3, catLabel } = kit;
  return function StackedBar(props) {
    let total = 0;
    for (const p of props.parts) total += p.value;
    const scale = props.max !== void 0 && props.max > total ? props.max : total;
    const free = props.max !== void 0 && props.max > total ? props.max - total : 0;
    const usedPct = scale > 0 ? total / scale * 100 : 0;
    const hovering = props.hoverKey !== null && props.hoverKey !== void 0;
    const showBox = free > 0 && hovering;
    let tip = null;
    if (props.hoverKey !== null && props.hoverKey !== void 0) {
      if (props.hoverKey === "free" && free > 0) {
        const pct = scale > 0 ? free / scale * 100 : 0;
        tip = {
          text: t("overview.free") + " " + fmt3(free) + " (" + Math.round(pct) + "%)",
          leftPct: Math.max(12, Math.min(total / scale * 100 + pct / 2, 88))
        };
      } else {
        let acc = 0;
        for (const p of props.parts) {
          const pct = scale > 0 ? p.value / scale * 100 : 0;
          if (p.key === props.hoverKey && p.value > 0) {
            tip = {
              // "(pct%)" is a share of the OCCUPIED total — the dashed box
              // that appears on hover frames exactly this reference region.
              text: catLabel(p.key) + " \u2248" + fmt3(p.value) + " (" + Math.round(p.value / total * 100) + "%) " + tr("overview.ofUsed"),
              leftPct: Math.max(12, Math.min(acc + pct / 2, 88))
            };
            break;
          }
          acc += pct;
        }
      }
    }
    return /* @__PURE__ */ React.createElement("div", { className: "lc-stacked-wrap" }, /* @__PURE__ */ React.createElement(
      "div",
      {
        className: "lc-stacked" + (hovering ? " lc-stacked-dim" : ""),
        style: { height: (props.height || 14) + "px" },
        onMouseLeave: () => {
          if (props.onHoverKey !== void 0) props.onHoverKey(null);
        }
      },
      total > 0 ? props.parts.map((p) => {
        if (!p.value) return null;
        const on = props.hoverKey !== void 0 && props.hoverKey === p.key;
        return /* @__PURE__ */ React.createElement(
          "div",
          {
            key: p.key,
            className: "lc-stacked-seg" + (on ? " lc-stacked-seg-on" : ""),
            style: { width: p.value / scale * 100 + "%", background: p.color },
            onMouseEnter: () => {
              if (props.onHoverKey !== void 0) props.onHoverKey(p.key);
            }
          }
        );
      }) : null,
      free > 0 ? /* @__PURE__ */ React.createElement(
        "div",
        {
          key: "free",
          className: "lc-stacked-free" + (props.hoverKey === "free" ? " lc-stacked-free-on" : ""),
          style: { width: free / scale * 100 + "%" },
          onMouseEnter: () => {
            if (props.onHoverKey !== void 0) props.onHoverKey("free");
          }
        }
      ) : null,
      showBox ? /* @__PURE__ */ React.createElement("div", { className: "lc-occupied-box", style: { width: usedPct + "%" } }) : null
    ), tip ? /* @__PURE__ */ React.createElement("div", { className: "lc-bar-tip", style: { left: tip.leftPct + "%" } }, tip.text) : null);
  };
}
function makeLegend(kit) {
  const { tr, fmt: fmt3, catLabel } = kit;
  return function Legend(props) {
    let total = 0;
    for (const p of props.parts) total += p.value;
    return /* @__PURE__ */ React.createElement("div", { className: "lc-legend" }, props.parts.map((p) => {
      const on = props.hoverKey !== void 0 && props.hoverKey === p.key;
      return /* @__PURE__ */ React.createElement(
        "span",
        {
          key: p.key,
          className: "lc-chip" + (on ? " lc-chip-on" : ""),
          title: tr("overview.ofUsed"),
          onMouseEnter: () => {
            if (props.onHoverKey !== void 0) props.onHoverKey(p.key);
          },
          onMouseLeave: () => {
            if (props.onHoverKey !== void 0) props.onHoverKey(null);
          }
        },
        /* @__PURE__ */ React.createElement("i", { style: { background: p.color } }),
        catLabel(p.key) + " \u2248" + fmt3(p.value),
        total > 0 ? /* @__PURE__ */ React.createElement("em", null, Math.round(p.value / total * 100) + "%") : null
      );
    }));
  };
}

// src/client/components/trendChart.tsx
function aggregateByTurn(requests) {
  const out = [];
  let runSteps = 0;
  for (const req of requests) {
    const last = out.length > 0 ? out[out.length - 1] : null;
    if (last !== null && (last.turn ?? 0) === (req.turn ?? 0)) {
      runSteps++;
      out[out.length - 1] = { ...req, stepCount: runSteps };
    } else {
      runSteps = 1;
      out.push({ ...req, stepCount: 1 });
    }
  }
  return out;
}
function attachMarkers(requests, events) {
  const markers = new Array(requests.length);
  for (const ev of events) {
    if (ev.kind !== "compaction" && ev.kind !== "prune") continue;
    for (let r = 0; r < requests.length; r++) {
      if (requests[r].seq >= ev.seq) {
        if (markers[r] === void 0) markers[r] = ev;
        break;
      }
    }
  }
  return markers;
}
function makeTrendChart(kit) {
  const { t, tr, fmt: fmt3, fmtTime: fmtTime2, catLabel, eventLabel, eventAt } = kit;
  const CHART_H = 112;
  const BAR_W = 14;
  const BAR_GAP = 2;
  const TURN_FILLS = ["rgba(128,128,128,0.12)", "rgba(128,128,128,0.26)"];
  return function TrendChart(props) {
    const requests = props.requests;
    const markers = props.markers;
    const anchorOf = (req) => typeof req.prompt === "number" && req.prompt > 0 && req.total > 0 ? req.prompt / req.total : 1;
    const barTotalOf = (req) => typeof req.prompt === "number" && req.prompt > 0 ? req.prompt : req.total;
    let maxTotal = 1;
    for (const req of requests) {
      const bt = barTotalOf(req);
      if (bt > maxTotal) maxTotal = bt;
    }
    const groups = [];
    for (const req of requests) {
      let grp = groups.length > 0 ? groups[groups.length - 1] : null;
      if (grp === null || grp.turn !== (req.turn ?? 0)) {
        grp = { turn: req.turn ?? 0, count: 0, span: 0, agg: req.stepCount !== void 0 };
        groups.push(grp);
      }
      grp.count++;
      grp.span += req.stepCount ?? 1;
    }
    const scrollRef = React.useRef(null);
    const scrolledOnce = React.useRef(false);
    const lastGranRef = React.useRef(props.granularity);
    const [edges, setEdges] = React.useState({ left: false, right: false });
    const edgesRef = React.useRef(edges);
    const updateEdges = (el) => {
      const left = el.scrollLeft > 4;
      const right = el.scrollLeft + el.clientWidth < el.scrollWidth - 4;
      const prev = edgesRef.current;
      if (prev.left === left && prev.right === right) return;
      edgesRef.current = { left, right };
      setEdges({ left, right });
    };
    React.useLayoutEffect(() => {
      const el = scrollRef.current;
      if (el === null) return;
      if (props.granularity !== lastGranRef.current) {
        lastGranRef.current = props.granularity;
        scrolledOnce.current = false;
      }
      if (!scrolledOnce.current) {
        scrolledOnce.current = true;
        el.scrollLeft = el.scrollWidth;
      } else if (el.scrollLeft + el.clientWidth >= el.scrollWidth - 24) {
        el.scrollLeft = el.scrollWidth;
      }
      updateEdges(el);
    });
    const tipOf = (req) => {
      const head = req.stepCount !== void 0 && req.stepCount > 1 ? tr("tip.turn", { t: req.turn ?? 0, n: req.stepCount }) : tr("tip.step", { t: req.turn ?? 0, s: req.step ?? 0 });
      return head + " \xB7 " + fmtTime2(req.time) + " \xB7 " + tr("tip.total", { n: fmt3(req.total) }) + (req.prompt !== void 0 ? " \xB7 " + tr("tip.actual", { n: fmt3(req.prompt) }) : "");
    };
    const hoveredIdx = props.hoveredSeq !== null ? requests.findIndex((r) => r.seq === props.hoveredSeq) : -1;
    const hoveredReq = hoveredIdx >= 0 ? requests[hoveredIdx] : null;
    return /* @__PURE__ */ React.createElement("div", { className: "lc-chartrow" }, /* @__PURE__ */ React.createElement("div", { className: "lc-axis" }, /* @__PURE__ */ React.createElement("span", { className: "lc-axis-top" }, fmt3(maxTotal)), /* @__PURE__ */ React.createElement("span", { className: "lc-axis-mid" }, fmt3(Math.round(maxTotal / 2))), /* @__PURE__ */ React.createElement("span", { className: "lc-axis-bot" }, "0")), /* @__PURE__ */ React.createElement(
      "div",
      {
        className: "lc-chart-scroll" + (props.activeTurn !== null ? " lc-chart-dim" : ""),
        ref: scrollRef,
        onScroll: (e) => {
          updateEdges(e.currentTarget);
        }
      },
      edges.left ? /* @__PURE__ */ React.createElement("div", { className: "lc-chart-fade lc-chart-fade-l" }) : null,
      /* @__PURE__ */ React.createElement(
        "div",
        {
          className: "lc-chart",
          onMouseLeave: () => {
            props.onHover(null);
          }
        },
        /* @__PURE__ */ React.createElement("div", { className: "lc-grid lc-grid-top" }),
        /* @__PURE__ */ React.createElement("div", { className: "lc-grid lc-grid-mid" }),
        requests.map((req, i) => {
          const marker = markers[i];
          const markerAt = marker !== void 0 ? eventAt(marker) : null;
          const selected = props.selectedSeq === req.seq;
          const hovered = props.hoveredSeq === req.seq;
          const inTurn = props.activeTurn !== null && (req.turn ?? 0) === props.activeTurn;
          return /* @__PURE__ */ React.createElement(
            "div",
            {
              key: req.seq,
              className: "lc-bar" + (selected ? " lc-bar-selected" : "") + (hovered ? " lc-bar-hovered" : "") + (inTurn ? " lc-bar-in-turn" : ""),
              style: { width: BAR_W + "px" },
              onClick: () => {
                props.onSelect(selected ? null : req.seq);
              },
              onMouseEnter: () => {
                props.onHover(req.seq);
              }
            },
            marker !== void 0 ? /* @__PURE__ */ React.createElement(
              "span",
              {
                className: "lc-bar-marker",
                title: "\u2702 " + (markerAt !== null ? markerAt + " \u2014 " : "") + eventLabel(marker)
              },
              "\u2702"
            ) : null,
            /* @__PURE__ */ React.createElement("div", { className: "lc-bar-stack" }, CATS.map((c) => {
              const v = (req[c.key] || 0) * anchorOf(req);
              if (!v) return null;
              return /* @__PURE__ */ React.createElement("div", { key: c.key, style: { height: Math.max(1, Math.round(v / maxTotal * CHART_H)) + "px", background: c.color } });
            }))
          );
        })
      ),
      hoveredReq !== null ? /* @__PURE__ */ React.createElement(
        "div",
        {
          className: "lc-chart-tip",
          style: { left: hoveredIdx * (BAR_W + BAR_GAP) + BAR_W / 2 + "px" }
        },
        tipOf(hoveredReq)
      ) : null,
      /* @__PURE__ */ React.createElement("div", { className: "lc-turns", onMouseLeave: () => {
        props.onHoverTurn(null);
      } }, groups.map((grp, gi) => {
        const on = props.activeTurn === grp.turn;
        const blockW = grp.agg ? BAR_W : grp.span * (BAR_W + BAR_GAP) - BAR_GAP;
        return /* @__PURE__ */ React.createElement(
          "span",
          {
            key: "turn-" + gi,
            className: "lc-turn" + (on ? " lc-turn-on" : ""),
            style: {
              width: blockW + "px",
              background: TURN_FILLS[gi % TURN_FILLS.length]
            },
            title: "T" + grp.turn,
            onMouseEnter: () => {
              props.onHoverTurn(grp.turn);
            }
          },
          "T" + grp.turn
        );
      }))
    ), edges.right ? /* @__PURE__ */ React.createElement("div", { className: "lc-chart-fade lc-chart-fade-r" }) : null);
  };
}

// src/client/components/contextModal.tsx
var TREND_TURNS = 10;
function makeContextModal(ctx, kit) {
  const { t, tr, fmt: fmt3 } = kit;
  const sessions = ctx.get("sessions");
  const StackedBar = makeStackedBar(kit);
  const Legend = makeLegend(kit);
  const TrendChart = makeTrendChart(kit);
  const RequestDetail = makeRequestDetail(kit, StackedBar);
  return function ContextModal(props) {
    const sessionId = typeof props.sessionId === "string" ? props.sessionId : "";
    const open = typeof props.useContextModal === "function" ? props.useContextModal((s) => s) : false;
    const data = typeof props.useProjection === "function" ? timelineOf(props.useProjection("contextTimeline")) : null;
    const pressure = typeof props.useProjection === "function" ? contextPressureOf(props.useProjection("contextPressure")) : null;
    const [selectedSeq, setSelectedSeq] = React.useState(null);
    const [hoveredSeq, setHoveredSeq] = React.useState(null);
    const [hoverCat, setHoverCat] = React.useState(null);
    const close = React.useCallback(() => {
      if (sessionId === "") return;
      modalStoreOf(sessionId).set(false);
      const guard = takePendingConsume(sessionId);
      if (guard === void 0 || sessions === void 0) return;
      const scope = sessions.scope(sessionId);
      if (scope !== void 0) scope.bail(scope, "slash/input-consume-token", { guard });
    }, [sessionId]);
    React.useEffect(() => {
      if (!open) return void 0;
      const previous = document.activeElement instanceof HTMLElement ? document.activeElement : null;
      const onKey = (ev) => {
        if (ev.key !== "Escape") return;
        ev.preventDefault();
        ev.stopPropagation();
        close();
      };
      window.addEventListener("keydown", onKey, true);
      return () => {
        window.removeEventListener("keydown", onKey, true);
        if (previous !== null && document.contains(previous)) previous.focus();
      };
    }, [open, close]);
    if (!open) return null;
    const requests = data !== null ? data.requests || [] : [];
    const events = data !== null ? data.events || [] : [];
    const turns = aggregateByTurn(requests).slice(-TREND_TURNS);
    const markers = attachMarkers(turns, events);
    let pinnedReq = null;
    for (const req of turns) if (req.seq === selectedSeq) pinnedReq = req;
    let activeReq = null;
    if (hoveredSeq !== null) {
      for (const req of turns) if (req.seq === hoveredSeq) activeReq = req;
    }
    if (activeReq === null) activeReq = pinnedReq;
    if (activeReq === null && turns.length > 0) activeReq = turns[turns.length - 1];
    const markerOf = (req) => {
      const i = turns.indexOf(req);
      return i >= 0 ? markers[i] : void 0;
    };
    const head = data !== null ? headlineOf(data, pressure) : null;
    return /* @__PURE__ */ React.createElement("div", { className: "lc-modal-backdrop", onClick: close }, /* @__PURE__ */ React.createElement("div", { className: "lc-modal-card", onClick: (ev) => {
      ev.stopPropagation();
    } }, /* @__PURE__ */ React.createElement("div", { className: "lc-modal-head" }, /* @__PURE__ */ React.createElement("span", { className: "lc-modal-title" }, t("tab")), data !== null && (data.model || data.provider) ? /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, (data.model ? data.model : "") + (data.provider ? " \xB7 " + data.provider : "")) : null, /* @__PURE__ */ React.createElement("button", { className: "lc-modal-close", "aria-label": t("cmd.close"), onClick: close }, "\xD7")), data === null || head === null ? /* @__PURE__ */ React.createElement("div", { className: "lc-empty" }, t("loading")) : /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { className: "lc-overview-num" }, /* @__PURE__ */ React.createElement("b", null, fmt3(head.tokens)), /* @__PURE__ */ React.createElement("span", null, head.window ? " / " + fmt3(head.window) + " " + tr("overview.ofWindow", { p: head.pct ?? 0 }) : " " + t("overview.estimate")), !head.estimated ? /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, t("overview.splitEst")) : null), /* @__PURE__ */ React.createElement(StackedBar, { parts: head.parts, height: 16, max: head.window, hoverKey: hoverCat, onHoverKey: setHoverCat }), /* @__PURE__ */ React.createElement(Legend, { parts: head.parts, hoverKey: hoverCat, onHoverKey: setHoverCat }), /* @__PURE__ */ React.createElement("div", { className: "lc-card-title lc-modal-trend" }, t("trend.title")), turns.length === 0 ? /* @__PURE__ */ React.createElement("div", { className: "lc-empty" }, t("trend.empty")) : /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement(
      TrendChart,
      {
        requests: turns,
        markers,
        selectedSeq: pinnedReq !== null ? pinnedReq.seq : null,
        hoveredSeq,
        activeTurn: null,
        granularity: "turn",
        onSelect: setSelectedSeq,
        onHover: setHoveredSeq,
        onHoverTurn: () => {
        }
      }
    ), /* @__PURE__ */ React.createElement(RequestDetail, { request: activeReq, marker: activeReq !== null ? markerOf(activeReq) : void 0 })))));
  };
}

// src/client/styles.ts
var STYLES = [
  ".lc-root { padding: 16px 20px 32px; overflow-y: auto; height: 100%; box-sizing: border-box; color: var(--dsw-alias-label-primary); font-size: 13px; }",
  ".lc-card { background: var(--dsw-alias-bg-layer-1); border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; padding: 14px 16px; margin-bottom: 14px; }",
  ".lc-card-title { font-weight: 600; margin-bottom: 10px; display: flex; align-items: baseline; gap: 8px; }",
  ".lc-stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(92px, 1fr)); gap: 8px; }",
  ".lc-stat { background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; padding: 8px 10px; display: flex; flex-direction: column; gap: 2px; min-width: 0; }",
  ".lc-stat-label { color: var(--dsw-alias-label-secondary); font-size: 11px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
  ".lc-stat-value { color: var(--dsw-alias-label-primary); font-size: 14px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; text-align: center; }",
  ".lc-stat-sub { color: var(--dsw-alias-label-secondary); font-size: 11px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
  ".lc-card-sub { font-weight: 400; color: var(--dsw-alias-label-secondary); font-size: 12px; }",
  ".lc-gran, .lc-kinds { margin-left: auto; display: flex; gap: 2px; background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; padding: 1px; }",
  ".lc-gran-btn { border: 0; background: transparent; color: var(--dsw-alias-label-secondary); font-size: 11px; line-height: 1; padding: 3px 8px; border-radius: 5px; cursor: pointer; font-family: inherit; }",
  ".lc-gran-btn:hover { color: var(--dsw-alias-label-primary); }",
  ".lc-gran-on, .lc-gran-on:hover { background: var(--dsw-alias-button-primary-fill); color: var(--dsw-alias-label-primary-foreground); }",
  ".lc-overview-num { margin-bottom: 8px; }",
  ".lc-overview-num b { font-size: 20px; }",
  ".lc-overview-num span { color: var(--dsw-alias-label-secondary); }",
  ".lc-stacked-wrap { position: relative; width: 100%; }",
  ".lc-stacked { display: flex; width: 100%; border-radius: 5px; overflow: hidden; background: rgba(128,128,128,0.18); position: relative; }",
  // Hover reference frame around the OCCUPIED region of the composition bar:
  // dashes from the left edge to the used/window boundary, so the legend's
  // "share of used" percentages visibly map to the boxed part (the free track
  // sits outside it). pointer-events: none keeps hover on the segments/free.
  // Deliberately high-contrast (label-primary) and thick so the frame reads at
  // a glance, and the other parts dim underneath it (`.lc-stacked-dim`).
  ".lc-occupied-box { position: absolute; top: 0; bottom: 0; left: 0; border: 2px dashed var(--dsw-alias-label-primary); border-radius: 5px; box-sizing: border-box; pointer-events: none; opacity: 1; box-shadow: 0 0 0 1px var(--dsw-alias-bg-layer-2); }",
  ".lc-bar-tip { position: absolute; bottom: calc(100% + 6px); transform: translateX(-50%); z-index: 5; white-space: nowrap; background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; padding: 3px 8px; font-size: 12px; color: var(--dsw-alias-label-primary); box-shadow: 0 2px 8px rgba(0,0,0,0.18); pointer-events: none; }",
  ".lc-stacked > div { height: 100%; }",
  ".lc-stacked-seg-on { filter: brightness(1.18); }",
  ".lc-stacked-free-on { box-shadow: inset 0 0 0 1px var(--dsw-alias-label-secondary); border-radius: 3px; }",
  // Hover focus: everything except the hovered part (segment, legend chip, or
  // free track) recedes, so the composition highlight and the occupied-region
  // frame read clearly. The selected segment/free keeps full opacity.
  ".lc-stacked-dim .lc-stacked-seg { opacity: 0.35; }",
  ".lc-stacked-dim .lc-stacked-seg-on { opacity: 1; }",
  ".lc-stacked-dim .lc-stacked-free { opacity: 0.35; }",
  ".lc-stacked-dim .lc-stacked-free-on { opacity: 1; }",
  ".lc-legend { display: flex; flex-wrap: wrap; gap: 6px 14px; margin-top: 10px; }",
  ".lc-chip { display: inline-flex; align-items: center; gap: 5px; color: var(--dsw-alias-label-primary); }",
  ".lc-chip i, .lc-detail-row i, .lc-node i { display: inline-block; width: 8px; height: 8px; border-radius: 2px; }",
  ".lc-chip em { font-style: normal; color: var(--dsw-alias-label-secondary); }",
  ".lc-chip-on { font-weight: 600; }",
  ".lc-chip-on i { box-shadow: 0 0 0 1px var(--dsw-alias-brand-primary); }",
  ".lc-tools { margin-top: 10px; color: var(--dsw-alias-label-secondary); display: flex; flex-wrap: wrap; gap: 6px; align-items: center; }",
  ".lc-tool-chip { background: var(--dsw-alias-bg-layer-2); border-radius: 4px; padding: 1px 7px; font-size: 12px; color: var(--dsw-alias-label-primary); }",
  ".lc-chartrow { display: flex; gap: 6px; align-items: stretch; }",
  ".lc-axis { position: relative; width: 40px; height: 150px; padding-top: 18px; box-sizing: border-box; color: var(--dsw-alias-label-secondary); font-size: 11px; }",
  ".lc-axis span { position: absolute; right: 0; line-height: 1; }",
  ".lc-axis-top { top: 13px; }",
  ".lc-axis-mid { top: 69px; }",
  ".lc-axis-bot { top: 125px; }",
  ".lc-chart-scroll { position: relative; flex: 1; overflow-x: auto; overflow-y: hidden; min-width: 0; scrollbar-width: thin; }",
  ".lc-chart-fade { position: absolute; top: 0; bottom: 0; width: 26px; pointer-events: none; z-index: 2; }",
  ".lc-chart-fade-l { left: 0; background: linear-gradient(to right, var(--dsw-alias-bg-layer-1), transparent); }",
  ".lc-chart-fade-r { right: 0; background: linear-gradient(to left, var(--dsw-alias-bg-layer-1), transparent); }",
  ".lc-chart { position: relative; display: flex; align-items: flex-end; gap: 2px; height: 130px; padding-top: 18px; box-sizing: border-box; width: max-content; min-width: 100%; }",
  ".lc-grid { position: absolute; left: 0; right: 0; border-top: 1px dashed var(--dsw-alias-border-l1); pointer-events: none; }",
  ".lc-grid-top { top: 18px; }",
  ".lc-grid-mid { top: 74px; }",
  ".lc-bar { position: relative; width: 14px; flex: none; height: 100%; display: flex; align-items: flex-end; cursor: pointer; border-radius: 2px; transition: opacity 120ms ease; }",
  // Turn-aware dimming: while a turn is focused, bars OUTSIDE the active
  // turn fade to 35% and the whole current turn stays fully opaque.
  ".lc-chart-dim .lc-bar { opacity: 0.35; }",
  ".lc-chart-dim .lc-bar-in-turn { opacity: 1; }",
  ".lc-chart-dim .lc-turn { opacity: 0.35; }",
  ".lc-chart-dim .lc-turn-on { opacity: 1; }",
  ".lc-chart-tip { position: absolute; top: 0; transform: translateX(-50%); z-index: 5; white-space: nowrap; background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; padding: 3px 8px; font-size: 12px; color: var(--dsw-alias-label-primary); box-shadow: 0 2px 8px rgba(0,0,0,0.18); pointer-events: none; }",
  ".lc-bar:hover { background: var(--dsw-alias-bg-layer-2); }",
  ".lc-bar-selected { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px; }",
  ".lc-bar-hovered { outline: 1px dashed var(--dsw-alias-brand-primary); outline-offset: 1px; }",
  ".lc-bar-in-turn { background: rgba(128,128,128,0.14); }",
  ".lc-bar-stack { display: flex; flex-direction: column-reverse; width: 100%; }",
  ".lc-bar-stack > div { width: 100%; }",
  ".lc-bar-marker { position: absolute; top: -16px; left: 50%; transform: translateX(-50%); font-size: 11px; color: var(--dsw-alias-state-warn-primary); }",
  // Turn strip: NEUTRAL zebra fills (inline, see TURN_FILLS) with secondary
  // text — never the category palette, or the strip reads as a detached
  // bottom segment of the bars above it.
  ".lc-turns { display: flex; gap: 2px; width: max-content; min-width: 100%; margin-top: 4px; }",
  ".lc-turn { flex: none; box-sizing: border-box; text-align: center; font-size: 10px; line-height: 14px; font-weight: 600; color: var(--dsw-alias-label-secondary); border-radius: 3px; height: 14px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; cursor: default; transition: filter 120ms, opacity 120ms; }",
  ".lc-turn-on { filter: brightness(1.35); color: var(--dsw-alias-label-primary); }",
  ".lc-detail { margin-top: 12px; border-top: 1px solid var(--dsw-alias-border-l1); padding-top: 12px; }",
  ".lc-detail-head { display: flex; flex-wrap: wrap; gap: 6px 16px; margin-bottom: 8px; color: var(--dsw-alias-label-secondary); }",
  ".lc-detail-head b { color: var(--dsw-alias-label-primary); }",
  ".lc-detail-marker { color: var(--dsw-alias-state-warn-primary); font-size: 11px; background: var(--dsw-alias-bg-layer-2); border-radius: 6px; padding: 1px 7px; }",
  ".lc-detail-head .lc-actual { color: var(--dsw-alias-state-success-primary); }",
  ".lc-detail-tag { background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 4px; padding: 0 6px; font-size: 11px; color: var(--dsw-alias-label-secondary); }",
  ".lc-detail-rows { margin-top: 10px; display: grid; grid-template-columns: 1fr 1fr; gap: 4px 24px; }",
  ".lc-detail-row { display: flex; align-items: center; gap: 8px; }",
  ".lc-detail-label { min-width: 70px; white-space: nowrap; color: var(--dsw-alias-label-secondary); }",
  ".lc-bar-track { flex: 1; height: 5px; border-radius: 3px; background: rgba(128,128,128,0.18); overflow: hidden; display: block; }",
  ".lc-bar-fill { display: block; height: 100%; border-radius: 3px; }",
  ".lc-detail-num { width: 44px; text-align: right; }",
  ".lc-detail-pct { width: 34px; text-align: right; color: var(--dsw-alias-label-secondary); }",
  // Section rows share one 14px vertical rhythm, owned by the ROW (flex gap
  // covers the wrapped-row axis too), never by the cards inside: a card that
  // IS a column (head, events/messages) drops its own bottom margin, and a
  // card stacked inside a wrapper column (overview + trend) keeps its margin
  // as the inner gap but the last one drops it — so every section boundary
  // measures exactly one 14px, whichever way the flex wraps.
  ".lc-cols { display: flex; gap: 14px; flex-wrap: wrap; margin-bottom: 14px; }",
  ".lc-col { flex: 1; min-width: 280px; }",
  ".lc-cols > .lc-card { margin-bottom: 0; }",
  ".lc-col > .lc-card:last-child { margin-bottom: 0; }",
  // Head row: stats board + plugin info sit side by side under the shared
  // `lc-cols` flex — stats takes ~7/10 of the row, plugin info ~3/10, both
  // wrap onto their own line when the available width falls below each card's
  // min-width (so a narrow viewport keeps both readable). Both children are
  // `.lc-card` themselves (rendered by StatsBoard / PluginInfo); the flex
  // sizing lives on the head row's direct children so the existing card
  // chrome doesn't change.
  ".lc-head > .lc-card:first-child { flex: 7 1 0; min-width: 360px; }",
  ".lc-head > .lc-card:last-child { flex: 3 1 0; min-width: 220px; }",
  // Plugin info: two full-width rows (Plugin / GitHub), each one horizontal
  // line with the label on the left and the value on the right — a compact
  // definition list rather than a multi-cell grid.
  ".lc-pi-grid { display: grid; grid-template-columns: 1fr; gap: 8px; }",
  // The row IS the link: an `<a>` with the label + value on one baseline.
  // Hovering a row underlines its value — the only hover affordance.
  ".lc-pi-row { display: flex; flex-direction: row; justify-content: space-between; align-items: baseline; gap: 12px; min-width: 0; text-decoration: none; color: inherit; }",
  ".lc-pi-row:hover .lc-pi-value { text-decoration: underline; }",
  // Upgrade chip appended to the Plugin value when the npm registry has a
  // newer version than the baked-in one.
  ".lc-pi-update { color: var(--dsw-alias-state-warn-primary); font-size: 11px; margin-left: 6px; white-space: nowrap; }",
  ".lc-pi-label { flex: none; color: var(--dsw-alias-label-secondary); font-size: 11px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
  // min-width: 0 lets the value shrink inside the flex row and truncate with
  // an ellipsis; without it a narrow card pushes the value over the label.
  ".lc-pi-value { min-width: 0; color: var(--dsw-alias-label-primary); font-size: 13px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; text-align: right; }",
  ".lc-events, .lc-nodes { display: flex; flex-direction: column; gap: 2px; max-height: 320px; overflow-y: auto; }",
  ".lc-event { display: flex; align-items: center; gap: 8px; padding: 3px 0; }",
  ".lc-event-icon { width: 18px; text-align: center; color: var(--dsw-alias-state-warn-primary); }",
  ".lc-event-icon.lc-event-inject { color: #a855f7; }",
  ".lc-event-icon.lc-event-model { color: var(--dsw-alias-brand-primary); }",
  // Kind chip: the event classification at a glance; the tint matches the
  // impact direction (inject = adds context, compaction/prune = frees it,
  // model switch = neutral), mirroring the token sign colors below.
  ".lc-kind { flex: none; font-size: 10px; font-weight: 600; padding: 1px 6px; border-radius: 4px; white-space: nowrap; }",
  ".lc-kind-inject { background: color-mix(in srgb, var(--dsw-alias-state-success-primary) 15%, transparent); color: var(--dsw-alias-state-success-primary); }",
  ".lc-kind-compaction { background: color-mix(in srgb, var(--dsw-alias-state-error-primary) 15%, transparent); color: var(--dsw-alias-state-error-primary); }",
  ".lc-kind-prune { background: color-mix(in srgb, #8b5cf6 15%, transparent); color: #8b5cf6; }",
  ".lc-kind-model { background: color-mix(in srgb, var(--dsw-alias-brand-primary) 15%, transparent); color: var(--dsw-alias-brand-primary); }",
  ".lc-event-label { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".lc-event-at { flex: none; color: var(--dsw-alias-label-secondary); font-size: 11px; white-space: nowrap; }",
  ".lc-event-tokens { color: var(--dsw-alias-state-success-primary); font-weight: 600; white-space: nowrap; }",
  ".lc-event-tokens.lc-up { color: var(--dsw-alias-state-warn-primary); }",
  ".lc-event-time { color: var(--dsw-alias-label-secondary); font-size: 12px; }",
  ".lc-node { display: flex; align-items: center; gap: 8px; padding: 3px 0; }",
  ".lc-node-preview { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--dsw-alias-label-primary); }",
  ".lc-node-time { color: var(--dsw-alias-label-secondary); font-size: 12px; min-width: 54px; text-align: right; }",
  ".lc-node-tokens { color: var(--dsw-alias-label-secondary); }",
  ".lc-nodes-more { color: var(--dsw-alias-label-secondary); padding: 3px 0; }",
  ".lc-empty { color: var(--dsw-alias-label-secondary); padding: 18px 0; text-align: center; }",
  ".lc-foot { color: var(--dsw-alias-label-secondary); font-size: 12px; margin-top: 4px; }",
  // ---- /context modal (centered dialog; escapes the composer anchor via fixed positioning) ----
  ".lc-modal-backdrop { position: fixed; inset: 0; z-index: 200; background: rgba(0, 0, 0, 0.45); display: flex; align-items: center; justify-content: center; }",
  ".lc-modal-card { width: min(720px, calc(100vw - 48px)); max-height: min(82vh, 760px); overflow-y: auto; box-sizing: border-box; background: var(--dsw-alias-bg-layer-1); border: 1px solid var(--dsw-alias-border-l1); border-radius: 12px; box-shadow: var(--dsw-shadow-lv3, 0 12px 32px rgba(0, 0, 0, 0.4)); padding: 16px 18px 18px; color: var(--dsw-alias-label-primary); font-size: 13px; }",
  ".lc-modal-head { display: flex; align-items: baseline; gap: 8px; margin-bottom: 12px; }",
  ".lc-modal-title { font-weight: 600; font-size: 14px; }",
  ".lc-modal-close { margin-left: auto; border: 0; background: transparent; color: var(--dsw-alias-label-secondary); font-size: 18px; line-height: 1; padding: 2px 6px; border-radius: 6px; cursor: pointer; font-family: inherit; }",
  ".lc-modal-close:hover { color: var(--dsw-alias-label-primary); background: var(--dsw-alias-bg-layer-2); }",
  ".lc-modal-trend { margin-top: 14px; }",
  // ---- Context browser card (progressive disclosure: category accordion ->
  // element rows -> per-kind content) ----
  ".lc-br-pick { margin-left: auto; font: inherit; font-size: 12px; color: var(--dsw-alias-label-primary); background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; padding: 3px 6px; max-width: 240px; }",
  ".lc-br-meta { display: flex; flex-wrap: wrap; gap: 6px 16px; margin-bottom: 8px; color: var(--dsw-alias-label-secondary); }",
  ".lc-br-meta b { color: var(--dsw-alias-label-primary); }",
  ".lc-br-meta .lc-actual { color: var(--dsw-alias-state-success-primary); }",
  ".lc-br-note { margin-top: 8px; color: var(--dsw-alias-label-secondary); font-size: 12px; }",
  ".lc-br-cats { margin-top: 10px; display: flex; flex-direction: column; gap: 4px; }",
  ".lc-br-cat { border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); overflow: hidden; }",
  ".lc-br-cat-empty { opacity: 0.55; }",
  ".lc-br-cat-row { display: flex; align-items: center; gap: 8px; width: 100%; border: 0; background: transparent; color: var(--dsw-alias-label-primary); font: inherit; padding: 7px 10px; cursor: pointer; text-align: left; }",
  ".lc-br-cat-row:hover { background: var(--dsw-alias-bg-layer-1); }",
  ".lc-br-cat-row i { display: inline-block; width: 8px; height: 8px; border-radius: 2px; flex: none; }",
  ".lc-br-cat-label { font-weight: 600; }",
  ".lc-br-cat-count { color: var(--dsw-alias-label-secondary); font-size: 12px; flex: 1; }",
  ".lc-br-chev { flex: none; width: 12px; color: var(--dsw-alias-label-secondary); transition: transform 120ms ease; }",
  ".lc-br-chev-on { transform: rotate(90deg); }",
  ".lc-br-tokens { flex: none; color: var(--dsw-alias-label-secondary); font-size: 12px; }",
  ".lc-br-pct { flex: none; width: 36px; text-align: right; color: var(--dsw-alias-label-secondary); font-size: 12px; }",
  ".lc-br-body { border-top: 1px solid var(--dsw-alias-border-l1); padding: 4px 6px; display: flex; flex-direction: column; gap: 2px; }",
  ".lc-br-elem { border-radius: 6px; }",
  ".lc-br-elem-on { background: var(--dsw-alias-bg-layer-1); }",
  ".lc-br-elem-row { display: flex; align-items: center; gap: 8px; width: 100%; border: 0; background: transparent; color: var(--dsw-alias-label-primary); font: inherit; font-size: 12px; padding: 5px 6px; cursor: pointer; text-align: left; border-radius: 6px; }",
  ".lc-br-elem-row:hover { background: var(--dsw-alias-bg-layer-1); }",
  ".lc-br-tag { flex: none; font-size: 11px; color: var(--dsw-alias-label-secondary); background: var(--dsw-alias-bg-layer-1); border: 1px solid var(--dsw-alias-border-l1); border-radius: 4px; padding: 0 6px; max-width: 220px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".lc-br-preview { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".lc-br-time { flex: none; color: var(--dsw-alias-label-secondary); font-size: 11px; }",
  ".lc-br-content { padding: 2px 6px 8px 26px; display: flex; flex-direction: column; gap: 6px; }",
  ".lc-br-pre { margin: 0; padding: 8px 10px; background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; color: var(--dsw-alias-label-primary); font-size: 12px; line-height: 1.55; white-space: pre-wrap; word-break: break-word; max-height: 320px; overflow-y: auto; scrollbar-width: thin; }",
  ".lc-br-dim { color: var(--dsw-alias-label-secondary); }",
  ".lc-br-call { display: flex; flex-direction: column; gap: 4px; align-items: flex-start; }"
].join("\n");

// src/client/assemble.ts
function headerAt(headers, seq) {
  if (headers === null || headers.headers.length === 0) return null;
  if (seq === null) return headers.headers[headers.headers.length - 1];
  for (let i = headers.headers.length - 1; i >= 0; i--) {
    if (headers.headers[i].seq < seq) return headers.headers[i];
  }
  return null;
}
function assemble(data, headers, seq) {
  const live = seq === null;
  let nodes;
  if (live) {
    nodes = data.nodes.slice();
  } else {
    const picked = [];
    for (const n of data.nodes) {
      if (n.seq < seq) picked.push(n);
    }
    for (const n of data.archive || []) {
      if (n.seq < seq && n.gone !== void 0 && n.gone > seq) picked.push(n);
    }
    nodes = picked;
  }
  nodes.sort((a, b) => a.seq - b.seq);
  let missingLive = 0;
  if (data.droppedNodes > 0) {
    if (live || data.surfaceFloor !== void 0 && seq > data.surfaceFloor) {
      missingLive = data.droppedNodes;
    }
  }
  const approximate = !live && data.archiveFloor !== void 0 && seq < data.archiveFloor;
  return { live, header: headerAt(headers, seq), nodes, missingLive, approximate };
}

// src/client/components/nodes.tsx
function makeNodeText(kit) {
  const { t } = kit;
  return function nodeText(n) {
    if (n.cat === "tool") {
      return t("node.toolResult") + (n.tool ? " \u2190 " + n.tool : "") + (n.err ? " \u26A0" : "");
    }
    if (n.skill) return "Skill: " + n.skill;
    if (n.calls) return t("node.calls") + n.calls.join(", ");
    if (n.text) return n.form === "snapshot" ? t("node.snapshot") + n.text : n.text;
    if (n.cat === "assistant") return t("node.empty");
    if (n.cat === "inject") return t("form." + (n.form || "context"));
    return t("node.nonText");
  };
}
function makeNodeList(kit) {
  const { t, tr, fmt: fmt3, fmtTime: fmtTime2 } = kit;
  const nodeText = makeNodeText(kit);
  return function NodeList(props) {
    if (props.nodes.length === 0) {
      return /* @__PURE__ */ React.createElement("div", { className: "lc-empty" }, t("nodes.empty"));
    }
    const catColor = {};
    for (const c of CATS) catColor[c.key] = c.color;
    const rows = props.nodes.slice().reverse();
    return /* @__PURE__ */ React.createElement("div", { className: "lc-nodes" }, props.dropped > 0 ? /* @__PURE__ */ React.createElement("div", { className: "lc-nodes-more" }, tr("nodes.more", { n: props.dropped })) : null, rows.map((n) => {
      const text = nodeText(n);
      return /* @__PURE__ */ React.createElement("div", { key: n.seq, className: "lc-node" }, /* @__PURE__ */ React.createElement("i", { style: { background: catColor[n.cat] || "#999" } }), /* @__PURE__ */ React.createElement("span", { className: "lc-node-preview", title: text }, text), typeof n.time === "number" ? /* @__PURE__ */ React.createElement("span", { className: "lc-node-time" }, fmtTime2(n.time)) : null, /* @__PURE__ */ React.createElement("span", { className: "lc-node-tokens" }, fmt3(n.tokens)));
    }));
  };
}

// src/client/components/browser.tsx
function RawBlocks(props) {
  return /* @__PURE__ */ React.createElement(React.Fragment, null, props.blocks.map((b, i) => {
    const blk = b;
    if (blk !== null && typeof blk === "object" && (blk.type === "text" || blk.type === "reasoning") && typeof blk.text === "string") {
      return /* @__PURE__ */ React.createElement("pre", { key: i, className: "lc-br-pre" + (blk.type === "reasoning" ? " lc-br-dim" : "") }, blk.text);
    }
    if (blk !== null && typeof blk === "object" && blk.type === "tool-result" && Array.isArray(blk.content)) {
      return /* @__PURE__ */ React.createElement(RawBlocks, { key: i, blocks: blk.content });
    }
    return /* @__PURE__ */ React.createElement("pre", { key: i, className: "lc-br-pre lc-br-dim" }, JSON.stringify(b, null, 2));
  }));
}
function NodeContent(props) {
  const { node, conv } = props;
  if (conv === void 0) {
    return /* @__PURE__ */ React.createElement("div", { className: "lc-br-content" }, node.text !== void 0 && node.text !== "" ? /* @__PURE__ */ React.createElement("pre", { className: "lc-br-pre" }, node.text) : null, /* @__PURE__ */ React.createElement("div", { className: "lc-br-note" }, props.hint));
  }
  if (conv.kind === "assistant" && Array.isArray(conv.blocks)) {
    return /* @__PURE__ */ React.createElement("div", { className: "lc-br-content" }, conv.blocks.map((b, i) => {
      const blk = b;
      if (blk.kind === "text" && typeof blk.text === "string") {
        return /* @__PURE__ */ React.createElement("pre", { key: i, className: "lc-br-pre" }, blk.text);
      }
      if (blk.kind === "reasoning" && typeof blk.text === "string") {
        return /* @__PURE__ */ React.createElement("pre", { key: i, className: "lc-br-pre lc-br-dim" }, blk.text);
      }
      if (blk.kind === "tool-call") {
        return /* @__PURE__ */ React.createElement("div", { key: i, className: "lc-br-call" }, /* @__PURE__ */ React.createElement("span", { className: "lc-br-tag" }, "\u2192 " + String(blk.name ?? "?")), typeof blk.argsRaw === "string" && blk.argsRaw !== "" ? /* @__PURE__ */ React.createElement("pre", { className: "lc-br-pre lc-br-dim" }, blk.argsRaw) : null);
      }
      return null;
    }));
  }
  if (conv.kind === "tool-result") {
    return /* @__PURE__ */ React.createElement("div", { className: "lc-br-content" }, conv.call != null ? /* @__PURE__ */ React.createElement("div", { className: "lc-br-call" }, /* @__PURE__ */ React.createElement("span", { className: "lc-br-tag" }, "\u2190 " + conv.call.name), conv.call.argsRaw !== "" ? /* @__PURE__ */ React.createElement("pre", { className: "lc-br-pre lc-br-dim" }, conv.call.argsRaw) : null) : null, Array.isArray(conv.content) ? /* @__PURE__ */ React.createElement(RawBlocks, { blocks: conv.content }) : null);
  }
  if (conv.kind === "compaction") {
    return /* @__PURE__ */ React.createElement("div", { className: "lc-br-content" }, typeof conv.summary === "string" && conv.summary !== "" ? /* @__PURE__ */ React.createElement("pre", { className: "lc-br-pre" }, conv.summary) : null);
  }
  if (Array.isArray(conv.content)) {
    return /* @__PURE__ */ React.createElement("div", { className: "lc-br-content" }, /* @__PURE__ */ React.createElement(RawBlocks, { blocks: conv.content }));
  }
  return /* @__PURE__ */ React.createElement("div", { className: "lc-br-content" }, /* @__PURE__ */ React.createElement("div", { className: "lc-br-note" }, props.hint));
}
function makeContextBrowser(kit, StackedBar) {
  const { t, tr, fmt: fmt3, fmtTime: fmtTime2, catLabel } = kit;
  const nodeText = makeNodeText(kit);
  const catColor = {};
  for (const c of CATS) catColor[c.key] = c.color;
  const MAX_AUTO_PAGES = 20;
  return function ContextBrowser(props) {
    var _a;
    const { data, headers } = props;
    const [sel, setSel] = React.useState("live");
    const [openCat, setOpenCat] = React.useState(null);
    const [openElem, setOpenElem] = React.useState(null);
    const convNodes = typeof props.useSession === "function" ? props.useSession((s) => s.nodes) : void 0;
    const bySeq = React.useMemo(() => {
      const m = /* @__PURE__ */ new Map();
      for (const n of convNodes ?? []) m.set(n.seq, n);
      return m;
    }, [convNodes]);
    const hasMore = typeof props.useSession === "function" ? props.useSession((s) => s.hasMore === true) : false;
    const loadingOlder = typeof props.useSession === "function" ? props.useSession((s) => s.loadingOlder === true) : false;
    const openSeq = openElem !== null && openElem.startsWith("n") ? Number(openElem.slice(1)) : null;
    const missingSeq = openSeq !== null && !bySeq.has(openSeq) ? openSeq : null;
    const [exhausted, setExhausted] = React.useState(false);
    const pagesRef = React.useRef(0);
    React.useEffect(() => {
      pagesRef.current = 0;
      setExhausted(false);
    }, [openElem]);
    const loadOlderHistory = props.loadOlderHistory;
    React.useEffect(() => {
      if (missingSeq === null || !hasMore || loadingOlder || exhausted) return;
      if (loadOlderHistory === void 0) return;
      if (pagesRef.current >= MAX_AUTO_PAGES) {
        setExhausted(true);
        return;
      }
      pagesRef.current += 1;
      void loadOlderHistory();
    }, [missingSeq, hasMore, loadingOlder, exhausted, bySeq, loadOlderHistory]);
    React.useEffect(() => {
      if (!hasMore && missingSeq !== null && !exhausted) setExhausted(true);
    }, [hasMore, missingSeq, exhausted]);
    const awaiting = missingSeq !== null && !exhausted && loadOlderHistory !== void 0 && hasMore;
    const requests = data.requests || [];
    const hoverReq = props.previewSeq !== null && props.previewSeq !== void 0 ? requests.find((r) => r.seq === props.previewSeq) ?? null : null;
    const req = hoverReq ?? (sel === "live" ? null : requests.find((r) => r.seq === sel) ?? null);
    const seq = req !== null ? req.seq : null;
    const view = assemble(data, headers, seq);
    const breakdown = req !== null ? req : data.current;
    const parts = partsOf(breakdown);
    const total = breakdown.total;
    const pick = (v) => {
      setSel(v === "live" ? "live" : Number(v));
      setOpenCat(null);
      setOpenElem(null);
    };
    const byCat = {};
    for (const n of view.nodes) (byCat[_a = n.cat] ?? (byCat[_a] = [])).push(n);
    const toolCount = (c) => {
      if (c === "system") return view.header !== null && view.header.system !== void 0 ? 1 : 0;
      if (c === "tools") return view.header !== null ? view.header.tools.length : 0;
      return byCat[c]?.length ?? 0;
    };
    const toggleCat = (c) => {
      const openable = toolCount(c) > 0 || (c === "system" || c === "tools") && view.header === null;
      if (!openable) return;
      setOpenCat(openCat === c ? null : c);
      setOpenElem(null);
    };
    const toggleElem = (key) => setOpenElem(openElem === key ? null : key);
    const elemRow = (key, tag, preview, tokens, time, body) => {
      const open = openElem === key;
      return /* @__PURE__ */ React.createElement("div", { key, className: "lc-br-elem" + (open ? " lc-br-elem-on" : "") }, /* @__PURE__ */ React.createElement("button", { type: "button", className: "lc-br-elem-row", onClick: () => {
        toggleElem(key);
      } }, /* @__PURE__ */ React.createElement("span", { className: "lc-br-chev" + (open ? " lc-br-chev-on" : "") }, "\u25B8"), tag !== null ? /* @__PURE__ */ React.createElement("span", { className: "lc-br-tag" }, tag) : null, /* @__PURE__ */ React.createElement("span", { className: "lc-br-preview" }, preview), time !== void 0 ? /* @__PURE__ */ React.createElement("span", { className: "lc-br-time" }, fmtTime2(time)) : null, /* @__PURE__ */ React.createElement("span", { className: "lc-br-tokens" }, "\u2248" + fmt3(tokens))), open ? body : null);
    };
    const catBody = (c) => {
      if (c === "system") {
        if (view.header === null) return /* @__PURE__ */ React.createElement("div", { className: "lc-br-note" }, t(headers === null ? "browser.noHeader" : "browser.noEpoch"));
        const system = view.header.system;
        if (system === void 0) return null;
        return elemRow(
          "sys",
          null,
          system.replace(/\s+/g, " ").trim().slice(0, 80),
          breakdown.system,
          void 0,
          /* @__PURE__ */ React.createElement("div", { className: "lc-br-content" }, /* @__PURE__ */ React.createElement("pre", { className: "lc-br-pre" }, system))
        );
      }
      if (c === "tools") {
        if (view.header === null) return /* @__PURE__ */ React.createElement("div", { className: "lc-br-note" }, t(headers === null ? "browser.noHeader" : "browser.noEpoch"));
        return view.header.tools.map((tool) => {
          const schema = tool.schema !== void 0 ? JSON.stringify(tool.schema, null, 2) : "";
          return elemRow(
            "tool:" + tool.name,
            null,
            tool.name,
            tool.tokens,
            void 0,
            /* @__PURE__ */ React.createElement("div", { className: "lc-br-content" }, tool.description !== void 0 ? /* @__PURE__ */ React.createElement("pre", { className: "lc-br-pre" }, tool.description) : null, schema !== "" ? /* @__PURE__ */ React.createElement("pre", { className: "lc-br-pre lc-br-dim" }, schema) : null)
          );
        });
      }
      const nodes = byCat[c] ?? [];
      return nodes.map((n) => {
        let tag = null;
        let preview = nodeText(n);
        if (n.cat === "tool") {
          tag = (n.tool ?? "?") + (n.err ? " \u26A0" : "");
          preview = t("node.toolResult") + (n.err ? " \u26A0" : "");
        } else if (n.cat === "inject" && !n.skill) {
          tag = t("form." + (n.form || "context"));
          if (n.text !== void 0 && n.text !== "") {
            preview = n.form === "snapshot" ? t("node.snapshot") + n.text : n.text;
          }
        }
        return elemRow(
          "n" + n.seq,
          tag,
          preview,
          n.tokens,
          n.time,
          /* @__PURE__ */ React.createElement(
            NodeContent,
            {
              node: n,
              conv: bySeq.get(n.seq),
              hint: bySeq.get(n.seq) === void 0 && awaiting ? t("browser.loading") : t("browser.noContent")
            }
          )
        );
      });
    };
    return /* @__PURE__ */ React.createElement("div", { className: "lc-card" }, /* @__PURE__ */ React.createElement("div", { className: "lc-card-title" }, t("browser.title"), /* @__PURE__ */ React.createElement(
      "select",
      {
        className: "lc-br-pick",
        value: seq === null ? "live" : String(seq),
        onChange: (e) => {
          pick(e.target.value);
        }
      },
      /* @__PURE__ */ React.createElement("option", { value: "live" }, t("browser.live")),
      requests.slice().reverse().map((r) => /* @__PURE__ */ React.createElement("option", { key: r.seq, value: String(r.seq) }, tr("detail.step", { t: r.turn ?? 0, s: r.step ?? 0 }) + " \xB7 " + fmtTime2(r.time)))
    )), /* @__PURE__ */ React.createElement("div", { className: "lc-br-meta" }, /* @__PURE__ */ React.createElement("b", null, req !== null ? tr("detail.step", { t: req.turn ?? 0, s: req.step ?? 0 }) : t("browser.liveNow")), req !== null ? /* @__PURE__ */ React.createElement("span", null, fmtTime2(req.time)) : null, hoverReq !== null ? /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, t("browser.preview")) : null, /* @__PURE__ */ React.createElement("span", null, tr("detail.estTotal", { n: fmt3(total) })), req !== null && req.prompt !== void 0 ? /* @__PURE__ */ React.createElement("span", { className: "lc-actual" }, tr("detail.actual", { n: fmt3(req.prompt) })) : null), /* @__PURE__ */ React.createElement(StackedBar, { parts, height: 10 }), view.missingLive > 0 ? /* @__PURE__ */ React.createElement("div", { className: "lc-br-note" }, tr("browser.missingLive", { n: view.missingLive })) : null, view.approximate ? /* @__PURE__ */ React.createElement("div", { className: "lc-br-note" }, t("browser.approx")) : null, /* @__PURE__ */ React.createElement("div", { className: "lc-br-cats" }, CATS.map((c) => {
      const count = toolCount(c.key);
      const v = breakdown[c.key] || 0;
      const openable = count > 0 || (c.key === "system" || c.key === "tools") && view.header === null;
      const open = openCat === c.key && openable;
      return /* @__PURE__ */ React.createElement("div", { key: c.key, className: "lc-br-cat" + (openable ? "" : " lc-br-cat-empty") }, /* @__PURE__ */ React.createElement("button", { type: "button", className: "lc-br-cat-row", onClick: () => {
        toggleCat(c.key);
      } }, /* @__PURE__ */ React.createElement("span", { className: "lc-br-chev" + (open ? " lc-br-chev-on" : "") }, "\u25B8"), /* @__PURE__ */ React.createElement("i", { style: { background: c.color } }), /* @__PURE__ */ React.createElement("span", { className: "lc-br-cat-label" }, catLabel(c.key)), /* @__PURE__ */ React.createElement("span", { className: "lc-br-cat-count" }, tr("browser.items", { n: count })), /* @__PURE__ */ React.createElement("span", { className: "lc-br-tokens" }, "\u2248" + fmt3(v)), /* @__PURE__ */ React.createElement("span", { className: "lc-br-pct" }, total > 0 ? Math.round(v / total * 100) + "%" : "")), open ? /* @__PURE__ */ React.createElement("div", { className: "lc-br-body" }, catBody(c.key)) : null);
    })));
  };
}

// src/client/components/events.tsx
var import_dsh_client_ui_primitives = require("@deepseek-ai/dsh-client-ui-primitives");

// src/client/format.ts
function fmt(n) {
  if (n === void 0 || n === null || isNaN(n)) return "\u2014";
  if (n >= 1e6) return (n / 1e6).toFixed(1) + "M";
  if (n >= 1e3) return (n / 1e3).toFixed(1) + "k";
  return String(Math.round(n));
}
function fmtTime(t) {
  const d = new Date(t);
  function p(x) {
    return (x < 10 ? "0" : "") + x;
  }
  return p(d.getHours()) + ":" + p(d.getMinutes()) + ":" + p(d.getSeconds());
}

// src/client/components/events.tsx
var EVENT_ICONS = { compaction: "\u2702", prune: "\u2702", inject: "\uFF0B", model: "\u21C4" };
function makeEventText(t, tr) {
  function eventLabel(ev) {
    if (ev.kind === "compaction") return tr("ev.compaction", { n: ev.count || 0 });
    if (ev.kind === "prune") return t("ev.prune");
    if (ev.kind === "model") return tr("ev.model", { a: ev.from || "?", b: ev.to || "?" });
    if (ev.kind === "inject") {
      if (ev.sub === "skill") return tr("ev.skill", { name: ev.name || "?" });
      const base = t("form." + (ev.form || "context"));
      return ev.name ? base + " \xB7 " + ev.name : base;
    }
    return ev.kind;
  }
  function eventAt(ev) {
    if (ev.kind === "compaction" || ev.kind === "prune") {
      if (typeof ev.turn === "number" && typeof ev.step === "number") {
        if (typeof ev.fromTurn === "number" && typeof ev.fromStep === "number") {
          if (ev.fromTurn === ev.turn) return t("events.range", { t: ev.turn, a: ev.fromStep, b: ev.step });
          return t("events.rangeTo", { a: ev.fromTurn, as: ev.fromStep, b: ev.turn, bs: ev.step });
        }
        return t("events.at", { t: ev.turn, s: ev.step });
      }
      return null;
    }
    if (typeof ev.turn === "number" && typeof ev.step === "number") {
      return t("events.at", { t: ev.turn, s: ev.step });
    }
    return null;
  }
  return { eventLabel, eventAt };
}
function makeEventList(kit) {
  const { t, fmt: fmt3, fmtTime: fmtTime2, eventLabel, eventAt } = kit;
  return function EventList(props) {
    if (props.events.length === 0) {
      return /* @__PURE__ */ React.createElement("div", { className: "lc-empty" }, t("events.empty"));
    }
    const rootRef = React.useRef(null);
    React.useLayoutEffect(() => {
      const root = rootRef.current;
      if (!root) return;
      const sync = () => {
        for (const el of root.querySelectorAll(".lc-event-label")) {
          el.title = el.scrollWidth > el.clientWidth ? el.textContent || "" : "";
        }
      };
      sync();
      window.addEventListener("resize", sync);
      return () => window.removeEventListener("resize", sync);
    });
    const sorted = props.events.slice().reverse();
    return /* @__PURE__ */ React.createElement("div", { className: "lc-events", ref: rootRef }, sorted.map((ev, i) => {
      const label = eventLabel(ev);
      const at = eventAt(ev);
      const glyph = ev.kind === "inject" ? /* @__PURE__ */ React.createElement(import_dsh_client_ui_primitives.IconPlusOutline16, null) : ev.kind === "model" ? /* @__PURE__ */ React.createElement(import_dsh_client_ui_primitives.IconBranchOutline16, null) : EVENT_ICONS[ev.kind] || "\u2022";
      return /* @__PURE__ */ React.createElement("div", { key: ev.seq + "-" + i, className: "lc-event" }, /* @__PURE__ */ React.createElement("span", { className: "lc-event-icon lc-event-" + ev.kind }, glyph), /* @__PURE__ */ React.createElement("span", { className: "lc-kind lc-kind-" + ev.kind }, t("kind." + ev.kind)), /* @__PURE__ */ React.createElement("span", { className: "lc-event-label" }, label), at !== null ? /* @__PURE__ */ React.createElement("span", { className: "lc-event-at" }, at) : null, ev.tokens ? /* @__PURE__ */ React.createElement("span", { className: "lc-event-tokens" + (ev.kind === "inject" ? " lc-up" : " lc-down") }, (ev.kind === "inject" ? "+" : "\u2212") + fmt3(ev.tokens)) : null, /* @__PURE__ */ React.createElement("span", { className: "lc-event-time" }, fmtTime2(ev.time)));
    }));
  };
}

// src/client/meta.ts
var PLUGIN_NAME = "dsh-context";
var PLUGIN_VERSION = true ? "0.12.1" : "0.0.0-dev";
var PLUGIN_REPO = true ? "https://github.com/bowenliang123/dsh-context" : "https://github.com/bowenliang123/dsh-context";
var PLUGIN_REPO_SHORT = PLUGIN_REPO.replace(/^https?:\/\/github\.com\//, "");

// src/client/latestVersion.ts
var REGISTRY_URL = "https://registry.npmjs.org/" + PLUGIN_NAME + "/latest";
var TTL_MS = 60 * 60 * 1e3;
var cached = null;
function fetchLatestVersion() {
  if (!cached || Date.now() - cached.at >= TTL_MS) {
    cached = {
      at: Date.now(),
      promise: fetch(REGISTRY_URL).then((res) => res.ok ? res.json() : null).then((body) => body && typeof body.version === "string" ? body.version : null).catch(() => null)
    };
  }
  return cached.promise;
}
function isNewerVersion(latest, current) {
  const parse = (v) => v.replace(/^v/, "").split("-", 1)[0].split(".").map((n) => parseInt(n, 10) || 0);
  const a = parse(latest);
  const b = parse(current);
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    const x = a[i] || 0;
    const y = b[i] || 0;
    if (x !== y) return x > y;
  }
  return false;
}

// src/client/components/pluginInfo.tsx
function makePluginInfo(kit) {
  const { t } = kit;
  const row = (label, value, href) => /* @__PURE__ */ React.createElement("a", { className: "lc-pi-row", href, target: "_blank", rel: "noreferrer" }, /* @__PURE__ */ React.createElement("div", { className: "lc-pi-label" }, label), /* @__PURE__ */ React.createElement("div", { className: "lc-pi-value" }, value));
  return function PluginInfo() {
    const [latest, setLatest] = React.useState(null);
    React.useEffect(() => {
      if (PLUGIN_VERSION.includes("-dev")) return;
      let on = true;
      fetchLatestVersion().then((v) => {
        if (on && v) setLatest(v);
      });
      return () => {
        on = false;
      };
    }, []);
    const update = latest !== null && isNewerVersion(latest, PLUGIN_VERSION) ? latest : null;
    const nameValue = [PLUGIN_NAME + " (v" + PLUGIN_VERSION + ")"];
    if (update) nameValue.push(/* @__PURE__ */ React.createElement("span", { key: "update", className: "lc-pi-update" }, "\u2191 v" + update));
    return /* @__PURE__ */ React.createElement("div", { className: "lc-card" }, /* @__PURE__ */ React.createElement("div", { className: "lc-card-title" }, t("plugin.title"), /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, t("plugin.hint"))), /* @__PURE__ */ React.createElement("div", { className: "lc-pi-grid" }, row(t("plugin.name"), nameValue, PLUGIN_REPO + "/releases"), row(t("plugin.github"), PLUGIN_REPO_SHORT, PLUGIN_REPO)));
  };
}

// src/client/components/statsBoard.tsx
function makeStatsBoard(kit) {
  const { t, fmt: fmt3 } = kit;
  return function StatsBoard(props) {
    const turns = /* @__PURE__ */ new Set();
    let steps = 0, compactions = 0, prunes = 0, injects = 0;
    for (const req of props.requests) {
      turns.add(req.turn ?? 0);
      steps++;
    }
    for (const ev of props.events) {
      if (ev.kind === "compaction") compactions++;
      else if (ev.kind === "prune") prunes++;
      else if (ev.kind === "inject") injects++;
    }
    const cell = (label, value) => /* @__PURE__ */ React.createElement("div", { className: "lc-stat" }, /* @__PURE__ */ React.createElement("span", { className: "lc-stat-label" }, label), /* @__PURE__ */ React.createElement("b", { className: "lc-stat-value" }, value));
    return /* @__PURE__ */ React.createElement("div", { className: "lc-card lc-col lc-col-stats" }, /* @__PURE__ */ React.createElement("div", { className: "lc-card-title" }, t("stats.title"), /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, t("stats.hint"))), /* @__PURE__ */ React.createElement("div", { className: "lc-stats" }, cell(t("stats.turns"), fmt3(turns.size)), cell(t("stats.steps"), fmt3(steps)), cell(t("stats.injects"), fmt3(injects)), cell(t("stats.compactions"), fmt3(compactions)), cell(t("stats.prunes"), fmt3(prunes))));
  };
}

// src/client/components/contextView.tsx
var viewScroll = /* @__PURE__ */ new Map();
var EVENT_KINDS = ["inject", "compaction", "prune", "model"];
function makeContextView(ctx, kit) {
  const { t, tr, fmt: fmt3, fmtTime: fmtTime2, catLabel } = kit;
  const StackedBar = makeStackedBar(kit);
  const Legend = makeLegend(kit);
  const TrendChart = makeTrendChart(kit);
  const RequestDetail = makeRequestDetail(kit, StackedBar);
  const EventList = makeEventList(kit);
  const NodeList = makeNodeList(kit);
  const StatsBoard = makeStatsBoard(kit);
  const PluginInfo = makePluginInfo(kit);
  const ContextBrowser = makeContextBrowser(kit, StackedBar);
  return function ContextView(props) {
    const sessionId = props.sessionId;
    const data = typeof props.useProjection === "function" ? timelineOf(props.useProjection("contextTimeline")) : null;
    const pressure = typeof props.useProjection === "function" ? contextPressureOf(props.useProjection("contextPressure")) : null;
    const headers = typeof props.useProjection === "function" ? headersOf(props.useProjection("contextHeaders")) : null;
    const [selectedSeq, setSelectedSeq] = React.useState(null);
    const [hoveredSeq, setHoveredSeq] = React.useState(null);
    const [hoverTurn, setHoverTurn] = React.useState(null);
    const [tick, setTick] = React.useState(0);
    const [granularity, setGranularity] = React.useState("step");
    const [hoverCat, setHoverCat] = React.useState(null);
    const [pickedKinds, setPickedKinds] = React.useState([...EVENT_KINDS]);
    const toggleKind = (k) => {
      setPickedKinds((p) => {
        if (p.length === EVENT_KINDS.length) return [k];
        if (!p.includes(k)) return [...p, k];
        return p.length === 1 ? [...EVENT_KINDS] : p.filter((x) => x !== k);
      });
    };
    const rootRef = React.useRef(null);
    const scrollerRef = React.useRef(null);
    const restoredRef = React.useRef(null);
    React.useLayoutEffect(() => {
      if (typeof sessionId !== "string" || sessionId === "" || data === null) return;
      if (restoredRef.current === sessionId) return;
      restoredRef.current = sessionId;
      const scroller = rootRef.current !== null ? rootRef.current.closest("[data-conversation-scroll]") : null;
      if (scroller === null) return;
      scrollerRef.current = scroller;
      scroller.scrollTop = viewScroll.get(sessionId) ?? 0;
    }, [sessionId, data]);
    React.useLayoutEffect(() => {
      return () => {
        if (typeof sessionId !== "string" || sessionId === "") return;
        const scroller = scrollerRef.current;
        if (scroller === null) return;
        viewScroll.set(sessionId, scroller.scrollTop);
      };
    }, [sessionId]);
    React.useEffect(() => {
      const localeSvc = ctx.get("locale");
      if (!localeSvc) return void 0;
      return localeSvc.subscribe(() => setTick((x) => x + 1));
    }, []);
    void tick;
    if (!data) {
      return /* @__PURE__ */ React.createElement("div", { className: "lc-root", ref: rootRef }, /* @__PURE__ */ React.createElement("div", { className: "lc-empty" }, t("loading")));
    }
    const requests = data.requests || [];
    const events = data.events || [];
    const shownEvents = pickedKinds.length === EVENT_KINDS.length ? events : events.filter((e) => pickedKinds.includes(e.kind));
    const nodes = data.nodes || [];
    const displayRequests = granularity === "turn" ? aggregateByTurn(requests) : requests;
    const markers = attachMarkers(displayRequests, events);
    const markerOf = (req) => {
      const i = displayRequests.indexOf(req);
      return i >= 0 ? markers[i] : void 0;
    };
    let pinnedReq = null;
    for (const req of displayRequests) if (req.seq === selectedSeq) pinnedReq = req;
    let activeReq = null;
    if (hoveredSeq !== null) {
      for (const req of displayRequests) if (req.seq === hoveredSeq) activeReq = req;
    }
    if (activeReq === null) activeReq = pinnedReq;
    if (activeReq === null && displayRequests.length > 0) activeReq = displayRequests[displayRequests.length - 1];
    let activeTurn = hoverTurn;
    if (activeTurn === null && hoveredSeq !== null) {
      for (const req of displayRequests) if (req.seq === hoveredSeq) {
        activeTurn = req.turn ?? null;
        break;
      }
    }
    const head = headlineOf(data, pressure);
    return /* @__PURE__ */ React.createElement("div", { className: "lc-root", ref: rootRef }, /* @__PURE__ */ React.createElement("div", { className: "lc-cols lc-head" }, /* @__PURE__ */ React.createElement(StatsBoard, { requests, events }), /* @__PURE__ */ React.createElement(PluginInfo, null)), /* @__PURE__ */ React.createElement("div", { className: "lc-cols" }, /* @__PURE__ */ React.createElement("div", { className: "lc-col" }, /* @__PURE__ */ React.createElement("div", { className: "lc-card" }, /* @__PURE__ */ React.createElement("div", { className: "lc-card-title" }, t("overview.title"), /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, (data.model ? data.model : "") + (data.provider ? " \xB7 " + data.provider : ""))), /* @__PURE__ */ React.createElement("div", { className: "lc-overview-num" }, /* @__PURE__ */ React.createElement("b", null, fmt3(head.tokens)), /* @__PURE__ */ React.createElement("span", null, head.window ? " / " + fmt3(head.window) + " " + tr("overview.ofWindow", { p: head.pct ?? 0 }) : " " + t("overview.estimate")), !head.estimated ? /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, t("overview.splitEst")) : null), /* @__PURE__ */ React.createElement(StackedBar, { parts: head.parts, height: 16, max: head.window, hoverKey: hoverCat, onHoverKey: setHoverCat }), /* @__PURE__ */ React.createElement(Legend, { parts: head.parts, hoverKey: hoverCat, onHoverKey: setHoverCat }), data.toolList && data.toolList.length > 0 ? /* @__PURE__ */ React.createElement("div", { className: "lc-tools" }, t("tools.top"), data.toolList.slice().sort((a, b) => b.tokens - a.tokens).slice(0, 5).map((tool) => {
      return /* @__PURE__ */ React.createElement("span", { key: tool.name, className: "lc-tool-chip" }, tool.name + " " + fmt3(tool.tokens));
    }), data.toolList.length > 5 ? /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, " " + tr("tools.more", { n: data.toolList.length })) : null) : null), /* @__PURE__ */ React.createElement("div", { className: "lc-card" }, /* @__PURE__ */ React.createElement("div", { className: "lc-card-title" }, t("trend.title"), /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, t("trend.hint")), /* @__PURE__ */ React.createElement("div", { className: "lc-gran" }, /* @__PURE__ */ React.createElement(
      "button",
      {
        className: "lc-gran-btn" + (granularity === "step" ? " lc-gran-on" : ""),
        onClick: () => {
          setGranularity("step");
        }
      },
      t("gran.step")
    ), /* @__PURE__ */ React.createElement(
      "button",
      {
        className: "lc-gran-btn" + (granularity === "turn" ? " lc-gran-on" : ""),
        onClick: () => {
          setGranularity("turn");
        }
      },
      t("gran.turn")
    ))), displayRequests.length === 0 ? /* @__PURE__ */ React.createElement("div", { className: "lc-empty" }, t("trend.empty")) : /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement(
      TrendChart,
      {
        key: sessionId,
        requests: displayRequests,
        markers,
        selectedSeq: pinnedReq ? pinnedReq.seq : null,
        hoveredSeq,
        activeTurn,
        granularity,
        onSelect: setSelectedSeq,
        onHover: setHoveredSeq,
        onHoverTurn: setHoverTurn
      }
    ), /* @__PURE__ */ React.createElement(RequestDetail, { request: activeReq, marker: activeReq !== null ? markerOf(activeReq) : void 0 })))), /* @__PURE__ */ React.createElement("div", { className: "lc-col" }, /* @__PURE__ */ React.createElement(
      ContextBrowser,
      {
        data,
        headers,
        useSession: props.useSession,
        loadOlderHistory: props.loadOlderHistory,
        previewSeq: hoveredSeq
      }
    ))), /* @__PURE__ */ React.createElement("div", { className: "lc-cols" }, /* @__PURE__ */ React.createElement("div", { className: "lc-card lc-col" }, /* @__PURE__ */ React.createElement("div", { className: "lc-card-title" }, t("events.title"), /* @__PURE__ */ React.createElement("div", { className: "lc-kinds" }, EVENT_KINDS.map((k) => /* @__PURE__ */ React.createElement(
      "button",
      {
        key: k,
        className: "lc-gran-btn" + (pickedKinds.includes(k) ? " lc-gran-on lc-kind-" + k : ""),
        onClick: () => {
          toggleKind(k);
        }
      },
      t("kind." + k)
    )))), /* @__PURE__ */ React.createElement(EventList, { events: shownEvents })), /* @__PURE__ */ React.createElement("div", { className: "lc-card lc-col" }, /* @__PURE__ */ React.createElement("div", { className: "lc-card-title" }, t("nodes.title"), /* @__PURE__ */ React.createElement("span", { className: "lc-card-sub" }, t("nodes.hint"))), /* @__PURE__ */ React.createElement(NodeList, { nodes, dropped: data.droppedNodes || 0 }))), /* @__PURE__ */ React.createElement("div", { className: "lc-foot" }, t("footer")));
  };
}

// src/client/viewkit.ts
function makeViewKit(t) {
  const { eventLabel, eventAt } = makeEventText(t, t);
  return {
    t,
    tr: t,
    fmt,
    fmtTime,
    catLabel: (key) => t("cat." + key),
    eventLabel,
    eventAt
  };
}

// src/client/index.ts
var NS = "dsh-context";
function apply(ctx) {
  ctx.effect(() => {
    return ctx.locale.register(NS, { zh: DICT_ZH, en: DICT_EN });
  }, "dsh-context: dictionaries");
  const t = ctx.locale.bind(NS);
  ctx.effect(() => {
    const tag = document.createElement("style");
    tag.setAttribute("data-plugin", "dsh-context");
    tag.textContent = STYLES;
    document.head.appendChild(tag);
    return () => {
      if (tag.parentNode !== null) tag.parentNode.removeChild(tag);
    };
  }, "dsh-context: styles");
  const kit = makeViewKit(t);
  const ContextView = makeContextView(ctx, kit);
  ctx.effect(() => {
    const noop = () => {
    };
    const sessions = ctx.get("sessions");
    if (sessions === void 0 || typeof sessions.provide !== "function") return noop;
    try {
      return sessions.provide({
        props: ["loadOlderHistory"],
        resolve: (binding) => ({ props: { loadOlderHistory: () => binding.session.loadOlder() } })
      });
    } catch {
      return noop;
    }
  }, "dsh-context: loadOlderHistory prop");
  ctx.slots.inject("conversation.view", () => {
    return ctx.slots.register(
      // order 20 renders right of Chat (0) and Trajectory (10); the locale
      // namespace put the framework `t` seat on the component's props too.
      { name: "conversation.view", id: "context", order: 20, locale: NS, label: () => t("tab") },
      (props) => h(ContextView, props)
    );
  });
  registerContextCommand(ctx, kit);
  const ContextModal = makeContextModal(ctx, kit);
  ctx.slots.inject("conversation.input.overlay", () => {
    return ctx.slots.register(
      {
        name: "conversation.input.overlay",
        id: "context-modal",
        order: 10,
        locale: NS,
        inject: (sessionId) => ({ hooks: { contextModal: modalStoreOf(sessionId) } })
      },
      (props) => h(ContextModal, props)
    );
  });
}
module.exports = {
  name: "dsh-context",
  inject: ["slots", "locale"],
  apply
};

    return module.exports;
  },
});
